name: Angular-CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "18"
         
      # Install dependencies
      - name: Install dependencies
        run: npm i

      # Run build for production
      - name: Build app bundle
        run: npm run build:prod  

      # Optionally, run tests
      - name: Run tests
        run: npm test

      # Deploy to Github pages
      - name: Deploy to Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: dist/portfolio-website/browser
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
