name: Angular-CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Setup nodejs
      - name: Setup nodejs
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "18"

      # Install dependencies
      - name: Install dependencies
        run: npm install

